name = "sri-vari-backend"
main = "src/index.js"
compatibility_date = "2024-02-12"

[vars]
# Add any environment variables here

[[d1_databases]]
binding = "DB"
database_name = "sri-vari-db"
database_id = "0859491d-1edb-40c9-ac88-19aee8a519b0"

[account]
id = "340badfe3c0958f9beb19c3cec27fe1f"

[observability]
enabled = true
